# Configures and deploys this Cloudflare Worker.
# Because Haiku OCR runs server-side code and this is how Cloudflare manages that.
# If the site doesn't require server-side code then this wrangler.toml file is not required.
name = "lee-transport-systems"
main = "worker.js"
compatibility_date = "2026-08-05"

# serves static files from root
[assets]
directory = ".."
